---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - run: yarn
      - run: yarn exec dxcli-semantic-release

workflows:
  version: 2
  "@dxcli/tslint":
    jobs:
      - release:
          context: org-global
          filters:
            branches: {only: master}
