---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
      DEPS: "nyc@11 @oclif/nyc-config@0 mocha-junit-reporter@1 @commitlint/cli@6 @commitlint/config-conventional@6"
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v0-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v0-yarn-{{checksum ".circleci/config.yml"}}
      - run: .circleci/greenkeeper
      - run: yarn add -D $DEPS
      - run: yarn test
      - run: yarn exec commitlint -- -x @commitlint/config-conventional --from origin/master
      - store_test_results: &store_test_results
          path: ~/cli/reports
  node-8:
    <<: *test
    docker:
      - image: node:8
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run: yarn
      - run: yarn global add @oclif/semantic-release@1 semantic-release@12
      - run: |
          export PATH=/usr/local/share/.config/yarn/global/node_modules/.bin:$PATH
          semantic-release -e @oclif/semantic-release
      - save_cache:
          key: v0-yarn-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  "@oclif/tslint":
    jobs:
      # - node-latest
      # - node-8
      - release:
          context: org-global
          filters:
            branches: {only: master}
          # requires:
          #   - node-latest
          #   - node-8
